---
- name: Set up kvm hosts
  hosts: kvm-hosts
  become: true
  gather_facts: True
  vars:
    common_sidecar: false
    common_node_exporter: false
    common_security: true
    common_docker: false
  roles:
    - common
    - kvm/hosts
#    - kvm/guest

