---
- name: update network interface
  template:
    src: netplan.yml.j2
    dest: /etc/netplan/enp2s0.yaml
    owner: root
    group: root
    mode: 0600

- name: add dnsmasq for host
  lineinfile:
    dest: "{{ libvirt_qemu_resolv_conf_head }}"
    regexp: "#DNS="
    line: "DNS=192.168.122.1"
  register: nameserver_result

- name: add dnsmasq for host
  lineinfile:
    dest: "{{ libvirt_qemu_resolv_conf_head }}"
    regexp: "#FallbackDNS="
    line: "FallbackDNS=192.168.1.254"
  register: nameserver_result

- name: restart systemd-resolved
  systemd:
    state: restarted
    daemon_reload: yes
    name: systemd-resolved
  when: nameserver_result.changed