---
- name: Creates directory
  file: path="{{vm_location}}" state=directory

- name: Install kvm and tools
  apt: name={{item}} state=present
  with_items:
       - qemu-kvm
       - libvirt-bin
       - libvirt-dev
       - virtinst
       - libguestfs-tools
       # Packages needed by ansible
       - pkg-config
       - python3-pip
       - python3-lxml

- name: start libvirtd
  service: name=libvirtd state=started enabled=yes
  register: libvirtd

- name: wait for libvirtd to get up
  pause: seconds=30
  when: libvirtd.changed


- name: Install libvirt-python
  pip:
    name: libvirt-python
    version: 4.0.0

- name: get list of vms
  virt: command=list_vms
  register: virt_vms
