---
- include_tasks: dependencies.yml
- include_tasks: bridge_network.yml
- include_tasks: update_virt_default_network.yml

#
- name: Enanable Iommu
  lineinfile:
    dest: /etc/default/grub
    regexp: 'GRUB_CMDLINE_LINUX_DEFAULT'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="intel_iommu=on"'
    state: present
  notify: update grub
