---
- set_fact:
     common_sidecar: "{{ common_sidecar | default(false) }}"
     common_node_exporter: "{{ common_node_exporter | default(false) }}"
     common_security: "{{ common_security | default(false) }}"
     common_docker: "{{ common_docker | default(false) }}"


- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600

- import_tasks: security.yml
  when: common_security

- import_tasks: sidecar.yml
  when: common_sidecar

- import_tasks: prometheus-exporter.yml
  when: common_node_exporter

- import_tasks: docker/main.yml
  when: common_docker