---
- name: Install security packages
  apt: name={{item}} state=present
  with_items:
       - ufw
       - fail2ban

- name: UFW Allow SSH
  ufw:
    rule: allow
    name: '{{ item }}'
  with_items:
    - OpenSSH

- name: Allow all access from RFC1918 networks to this host
  ufw:
    rule: allow
    src: '{{ item }}'
  with_items: "{{whitelisted_ips | default([]) }}"

- name: Secure instance
  ufw:
    state: enabled