---
- name: Esure Shutdown of guest before clone
  include_tasks: shutdown.yml
  vars:
     guest_name: "{{guest.value.base_guest}}"

- name: create vm
  command: >
            virt-clone
            --original {{ guest.value.base_guest }}
            --name {{ guest.value.name }}
            --file {{ vm_location }}/{{ guest.value.name }}.{{ guest.value.file_type }}

- name: set vm to autostart
  command: virsh autostart {{ guest.value.name }}

- name: Boot guests
  include_tasks: start.yml